#! /bin/sh

_ROOT="$(pwd)" && cd "$(dirname "$0")" && ROOT="$(pwd)"

IPLISTLINK="https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt"
IPNAME=chinaip

echo "Fetching latest [china_ip_list.txt]..."
CONTENT="$(curl -s "$IPLISTLINK")"
if [ $? -ne 0 ]; then
    exit 1
fi

echo "Putting into file [$IPNAME]..."
echo -n "$CONTENT" >$IPNAME

echo "Done!"
