#! /bin/sh

_ROOT="$(pwd)" && cd "$(dirname "$0")" && ROOT="$(pwd)"

REPO="$(dirname "$ROOT")"
GIT=git
DNS=8.8.8.8

cd $REPO

# domain
fold="$(sha1sum domains/gfwlist)"
domains/update-gfwlist

fnew="$(sha1sum domains/gfwlist)"
if [ "$fnew" != "$fold" ]; then
    $ROOT/gen-dnsmasq $DNS
fi

# ip
$REPO/ips/update-china-ip-list

$GIT status -s | grep -qP '^\s*M\s+'
if [ $? -eq 0 ]; then
    echo "pushing..."
    $GIT add domains/gfwlist
    $GIT add tools/dnsmasq-$DNS
    $GIT add ips/chinaip
    $GIT commit -m "Auto Commit at $(date +'%Y-%m-%d %H:%M:%S %Z')"
    $GIT push
fi
