#! /bin/sh

_ROOT="$(pwd)" && cd "$(dirname "$0")" && ROOT="$(pwd)"

REPO="$(dirname "$ROOT")"
GIT=git
DNS=auto

cd $REPO

# ip
$REPO/ips/update-china-ip-list

# domain
mkdir -p tmp
fold="$(sha1sum tmp/gfwlist)"
domains/update-gfwlist

fnew="$(sha1sum domains/gfwlist)"
if [ "$fnew" != "$fold" ]; then
    $ROOT/gen-dnsmasq $DNS
    $ROOT/gen-autoproxy
    cp domains/gfwlist tmp/gfwlist
fi

$GIT status -s | grep -qP '^\s*M\s+'
if [ $? -eq 0 ]; then
    echo "pushing..."
    $GIT add domains/gfwlist
    $GIT add tools/dnsmasq-*
    $GIT add tools/chinanet.txt
    $GIT add ips/chinaip
    $GIT commit -m "Auto Commit at $(date +'%Y-%m-%d %H:%M:%S %Z')"
    $GIT push
fi
