#! /bin/sh

_ROOT="$(pwd)" && cd "$(dirname "$0")" && ROOT="$(pwd)"

if [ -z "$1" ]; then
    echo "Usage: $0 {dns ip}"
    echo "e.g. $0 8.8.8.8"
    exit
fi

if [ "$1" = "auto" ]; then
    echo $0 1.1.1.1
    $0 1.1.1.1

    echo $0 8.8.8.8
    $0 8.8.8.8

    echo $0 127.0.0.1#54
    $0 127.0.0.1#54

    exit 0
fi

echo -n "$1" | grep -P -q '^\d+(\.(\d+)){3,3}(#\d+)?$'
if [ $? -ne 0 ]; then
    echo "[ERROR] Invalid dns ip format => $1"
    exit 1
fi

DNS=$1
FNAME=$ROOT/dnsmasq-$DNS
truncate -s0 $FNAME

NAMESDIR="$(dirname $ROOT)/domains"

output() {
    while read name; do
        name="$(echo -n "$name" | sed -r -n 's;^\s*([0-9a-z-]+(\.[0-9a-z-]+)*)\s*$;\1;ip')"
        [ -n "$name" ] && echo "server = /$name/$1"
    done
}

echo "# China company that use TLD exclude cn" >>$FNAME
output '#' <$NAMESDIR/cn-tld >>$FNAME
echo >>$FNAME

echo "# gfw-extra" >>$FNAME
output $DNS <$NAMESDIR/gfw-extra >>$FNAME
echo >>$FNAME

echo "# gTLD" >>$FNAME
output $DNS <$NAMESDIR/gtld >>$FNAME
echo >>$FNAME

echo "# gfwlist" >>$FNAME
output $DNS <$NAMESDIR/gfwlist >>$FNAME
